fix if authors field is empty for api data
khubo/literead pull request #1
Opened 2019-01-11 06:53 UTC by safaldas

2019-01-11 15:59 UTC, khubo requested changes

2019-01-11 15:59 UTC, khubo commented on src/containers/Searchbar.js
> +          onKeyPress={event => {
maybe  move this function logic out of here. Also, in general its better to avoid using anonymous functions in prop ;)

2019-01-11 15:59 UTC, khubo commented
maybe squash the commit into one as well?

2019-01-14 06:23 UTC, safaldas commented
okay now? i rebased idk if this is what you meant

2019-01-14 14:44 UTC, khubo approved these changes

2019-01-14 14:45 UTC, merged